backend:
  name: git-gateway
  branch: gridsome

media_folder: 'static/uploads'
public_folder: '/uploads'

# publish_mode: editorial_workflow
show_preview_links: true

collections:
  - name: 'photography'
    label: 'Photography Post'
    folder: 'photography'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: true }
      - {
          label: 'Cover Image',
          name: 'cover_image',
          widget: 'image',
          required: true,
        }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          # default: ["post"],
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  #
  - name: 'writing'
    label: 'Writing Post'
    folder: 'writing'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'date' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          # default: ["post"],
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    #
  - name: 'portfolio'
    label: 'Portfolio Item'
    folder: 'portfolio'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Order', name: 'order', widget: 'number', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Image', name: 'image', widget: 'image', required: true }
      - {
          label: 'Link Name',
          name: 'link_name',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Link URL',
          name: 'link_url',
          widget: 'string',
          required: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  #
